[package]
name = "txt2npq"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
byteorder = "1.5.0"

[dev-dependencies]
tempfile = "3.10.1"

[[test]]
name = "end_to_end"
path = "tests/end_to_end.rs"